# Generated by Django 5.2.17 on 2026-09-25 12:08

import django.db.models.deletion
import django.utils.timezone
import monitors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=2048)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('failure_threshold', models.PositiveSmallIntegerField(default=2)),
                ('recovery_threshold', models.PositiveSmallIntegerField(default=1)),
                ('retention_policy', models.CharField(choices=[('48_HOURS', '48 hours'), ('7_DAYS', '7 days'), ('14_DAYS', '14 days'), ('30_DAYS', '30 days'), ('FOREVER', 'Forever')], default='30_DAYS', max_length=10)),
                ('follow_redirects', models.BooleanField(default=True)),
                ('accepted_status_ranges', models.JSONField(default=monitors.models.default_accepted_status_ranges)),
                ('status', models.CharField(blank=True, choices=[('UP', 'Up'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('PAUSED', 'Paused')], max_length=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'enabled', 'next_check_at'], name='monitors_mo_owner_i_ce2354_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('interval_seconds__gte', 30), ('interval_seconds__lte', 86400)), name='monitor_interval_range'), models.CheckConstraint(condition=models.Q(('timeout_seconds__gte', 1), ('timeout_seconds__lte', 30)), name='monitor_timeout_range'), models.CheckConstraint(condition=models.Q(('failure_threshold__gte', 1), ('failure_threshold__lte', 5)), name='monitor_failure_threshold_range'), models.CheckConstraint(condition=models.Q(('recovery_threshold__gte', 1), ('recovery_threshold__lte', 5)), name='monitor_recovery_threshold_range')],
            },
        ),
    ]
