# Generated by Django 5.2.17 on 2026-09-27 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('error_type', models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS error'), ('CONNECTION_ERROR', 'Connection error'), ('SSL_ERROR', 'SSL error'), ('TOO_MANY_REDIRECTS', 'Too many redirects')], max_length=30, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at', '-id'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='monitors_ch_monitor_24c7e4_idx')],
            },
        ),
    ]
