# Generated by Django 5.2.17 on 2026-09-30 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_checks', models.PositiveBigIntegerField(default=0)),
                ('successful_checks', models.PositiveBigIntegerField(default=0)),
                ('failed_checks', models.PositiveBigIntegerField(default=0)),
                ('total_response_time_ms', models.PositiveBigIntegerField(default=0)),
                ('min_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'date'), name='unique_daily_metric_monitor_date')],
            },
        ),
    ]
