# Generated by Django 5.2.17 on 2026-09-30 05:46

import django.db.models.deletion
import monitors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_dailymetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicStatusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=monitors.models.default_public_status_slug, max_length=80, unique=True)),
                ('title', models.CharField(default='Service status', max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitors', models.ManyToManyField(blank=True, related_name='public_status_pages', to='monitors.monitor')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_status_page', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_id'],
            },
        ),
    ]
